version: '3'

tasks:
  install:
    cmds:
      - |
        mvn install && \
        mvn --file pom.xml install
  # Create a release commit
  release-commit:
    cmds:
      - |        
        set -TCEeuo pipefail
        
        export NEXT_VERSION=$(yq --exit-status '.project.version' pom.xml | sed 's/-SNAPSHOT$//')
        
        ./mvnw versions:set -DgenerateBackupPoms=false -DnewVersion=$NEXT_VERSION
        
        git commit -am "chore(release): $NEXT_VERSION"
        git push origin
  # Create a snapshot commit
  snapshot-commit:
    cmds:
      - |
        set -TCEeuo pipefail
        
        ./mvnw versions:set -DgenerateBackupPoms=false -DnextSnapshot=true 
        # manually mvnw versions:set -DgenerateBackupPoms=false -DnewVersion=x.y.z-SNAPSHOT
        
        NEXT_VERSION=$(yq --exit-status '.project.version' pom.xml)
        git commit -am "chore(next): $NEXT_VERSION"
        git push origin
